INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'IT');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'MARKETING');

INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT_ID) VALUES (1, 'john vanbiesbrouck', 1);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT_ID) VALUES (2, 'Ricky Martin', 1);
INSERT INTO EMPLOYEE (ID, NAME, DEPARTMENT_ID) VALUES (3, 'Joey Zasa', 2);
