CREATE TABLE DEPARTMENT
(
	ID NUMBER(19) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
);


CREATE TABLE EMPLOYEE
(
	ID NUMBER(19) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	DEPARTMENT_ID NUMBER(19) NOT NULL,
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);